# This file is a template. This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: node:15

before_script:
  - npm install



# List of stages for jobs, and their order of execution
stages:
  - test
  - staging
  - production

## Jobs to run in Test environment

build-test-job:
  stage: test
  script:
    - echo "Building the code..."
    - echo "Build successfully completed."

unit-test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - echo "Compiling the code..."
    - npm test
    - echo "Compile complete."

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the test stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - npm test
    - echo "All unit tests passed"

## Jobs to run in Staging environment

build-staging-job:
  stage: staging
  script:
    - echo "Building the code..."
    - echo "Build successfully completed."

unit-staging-job:   # This job runs in the staging stage.
  stage: staging    # It only starts when the job in the test stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - npm test
    - echo "All unit tests passed"

## Jobs to run in Production environment

build-production-job:
  stage: production
  script:
    - echo "Building the code..."
    - echo "Build successfully completed."

unit-production-job:   # This job runs in the staging stage.
  stage: production    # It only starts when the job in the test stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - npm test
    - echo "All unit tests passed"

deploy-job:      # This job runs in the production stage.
  stage: production  # It only runs when *both* jobs in the staging stage complete successfully.
  needs:
    job: build-production-job
    job: unit-production-job
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
